"""
Shared constants and helper functions for the orchestrator.
This module breaks circular dependencies between orchestrateur_general.py and graph_nodes.
"""

# Action sets
ACTIONS_LECTURE = {
    "TOP_CLIENTS", "LISTE_CLIENTS", "LISTE_ARTICLES", "PALMARES_ARTICLES",
    "CA_GLOBAL", "CLIENTS_BAISSE", "CLIENTS_INACTIFS", "FACTURES_NON_REGLEES", "FACTURES_NON_REGLEES_FOURN",
    "TOUTES_FACTURES_CLIENT", "VERIFIER_STOCK", "FICHE_CLIENT",
    "DOCS_PERIODE", "RENTABILITE", "SAISONNALITE", "DSO", "RFM", "STATUT_CLIENT",
    "LISTE_FOURNISSEURS", "FICHE_FOURNISSEUR", "TOP_FOURNISSEURS",
}

ACTIONS_NL2SQL = {"NL2SQL_LIBRE"}

ACTIONS_EXPORT = {
    "OFFRE_PRIX_EXCEL", "DECLARATION_EXCEL",
    "BALANCE_AGEE_EXCEL", "DASHBOARD_EXCEL",
}

ACTIONS_ECRITURE = {
    "CREER_CLIENT", "CREER_FOURNISSEUR", "MODIFIER_STATUT", "GENERER_DOC",
    "TRANSFORMER_DOC", "CREER_AVOIR", "REGLEMENT",
    "MOUVEMENT_STOCK", "PROPOSITION_ACHAT", "MODIFIER_ENTITE",
}

ACTIONS_WORKFLOW = {"WORKFLOW_COMMANDE"}

ACTIONS_KB = {
    "RECHERCHE_PROCEDURE", "RECOMMANDATION",
    "SEUIL_STOCK", "LISTE_PROCEDURES",
}

ACTIONS_HUB = {
    "VALIDER_DEMANDE", "RESOUDRE_TYPE_DOC",
    "GET_SCHEMA", "CONTEXTE_CLIENT",
}

ACTIONS_ENRICHIR_RAG = {"CLIENTS_BAISSE", "CLIENTS_INACTIFS", "DSO", "FACTURES_NON_REGLEES", "RFM"}

ACTIONS_SYNTHESE_LITE = {
    "GENERER_DOC", "TRANSFORMER_DOC", "CREER_AVOIR", "REGLEMENT",
    "MODIFIER_STATUT", "CREER_CLIENT", "CREER_FOURNISSEUR", "MOUVEMENT_STOCK", "FACTURES_NON_REGLEES_FOURN",
    "VERIFIER_STOCK", "FICHE_CLIENT", "STATUT_CLIENT",
}

# Document types
TYPES_DOC_FABRICATION = {"OF", "BF"}

# MCP error statuses
_STATUTS_ERREUR_MCP = {
    "CLIENT_NON_TROUVE", "CLIENT_BLOQUE", "ARTICLE_NON_TROUVE",
    "STOCK_INSUFFISANT", "COMPOSANTS_INSUFFISANTS", "NON_TROUVE", "EXISTE_DEJA",
}
